<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('solicitud', function (Blueprint $table) {
            $table->engine="InnoDB";
            $table->id();
            $table->foreignId('usuario_id')
                ->constrained('usuario')
                ->onDelete('cascade');
            $table->foreignId('producto_id')
                ->constrained('producto')
                ->onDelete('cascade');
            $table->string('tipo', 20);
            $table->string('descripcion', 250);
            $table->integer('cantidad');
            $table->date('fecha');
            $table->string('estado', 50);
        });

        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','1','Pedido','Estimado se le solicita el producto: ','4','2022-03-05','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','1','Pedido','Estimado se le solicita el producto: ','6','2023-05-15','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','1','Pedido','Estimado se le solicita el producto: ','6','2023-06-03','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','1','Pedido','Estimado se le solicita el producto: ','7','2024-02-01','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','1','Pedido','Estimado se le solicita el producto: ','7','2024-06-08','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','2','Pedido','Estimado se le solicita el producto: ','5','2022-04-03','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','2','Pedido','Estimado se le solicita el producto: ','7','2023-02-11','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','2','Pedido','Estimado se le solicita el producto: ','4','2023-04-03','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','2','Pedido','Estimado se le solicita el producto: ','3','2024-02-04','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','2','Pedido','Estimado se le solicita el producto: ','1','2024-03-05','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('3','3','Pedido','Estimado se le solicita el producto: ','3','2022-07-04','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('3','3','Pedido','Estimado se le solicita el producto: ','5','2023-05-12','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('3','3','Pedido','Estimado se le solicita el producto: ','2','2023-08-06','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('3','3','Pedido','Estimado se le solicita el producto: ','5','2024-03-18','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('3','3','Pedido','Estimado se le solicita el producto: ','5','2024-05-29','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','4','Pedido','Estimado se le solicita el producto: ','10','2022-05-26','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','4','Pedido','Estimado se le solicita el producto: ','6','2023-05-05','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','4','Pedido','Estimado se le solicita el producto: ','4','2023-06-23','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','4','Pedido','Estimado se le solicita el producto: ','8','2024-03-26','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','4','Pedido','Estimado se le solicita el producto: ','2','2024-07-08','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','5','Pedido','Estimado se le solicita el producto: ','4','2022-01-12','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','5','Pedido','Estimado se le solicita el producto: ','5','2023-10-28','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','5','Pedido','Estimado se le solicita el producto: ','1','2023-11-25','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','5','Pedido','Estimado se le solicita el producto: ','5','2024-02-21','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','5','Pedido','Estimado se le solicita el producto: ','5','2024-06-03','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','6','Pedido','Estimado se le solicita el producto: ','4','2022-07-01','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','6','Pedido','Estimado se le solicita el producto: ','3','2023-10-13','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','6','Pedido','Estimado se le solicita el producto: ','3','2023-12-01','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','6','Pedido','Estimado se le solicita el producto: ','4','2024-04-24','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','6','Pedido','Estimado se le solicita el producto: ','6','2024-05-27','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','7','Pedido','Estimado se le solicita el producto: ','4','2022-03-26','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','7','Pedido','Estimado se le solicita el producto: ','3','2023-04-15','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','7','Pedido','Estimado se le solicita el producto: ','9','2023-09-03','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','7','Pedido','Estimado se le solicita el producto: ','2','2024-01-22','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','7','Pedido','Estimado se le solicita el producto: ','12','2024-06-08','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','8','Pedido','Estimado se le solicita el producto: ','4','2022-03-03','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','8','Pedido','Estimado se le solicita el producto: ','6','2023-03-01','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','8','Pedido','Estimado se le solicita el producto: ','6','2023-10-05','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','8','Pedido','Estimado se le solicita el producto: ','7','2024-03-25','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','8','Pedido','Estimado se le solicita el producto: ','7','2024-06-06','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','9','Pedido','Estimado se le solicita el producto: ','4','2022-07-01','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','9','Pedido','Estimado se le solicita el producto: ','8','2023-05-13','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','9','Pedido','Estimado se le solicita el producto: ','4','2023-05-25','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','9','Pedido','Estimado se le solicita el producto: ','3','2024-05-05','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','9','Pedido','Estimado se le solicita el producto: ','11','2024-05-28','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','10','Pedido','Estimado se le solicita el producto: ','5','2022-04-07','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','10','Pedido','Estimado se le solicita el producto: ','8','2023-10-20','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','10','Pedido','Estimado se le solicita el producto: ','3','2023-11-25','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','10','Pedido','Estimado se le solicita el producto: ','7','2024-01-01','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','10','Pedido','Estimado se le solicita el producto: ','7','2024-05-29','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','185','Pedido','Estimado se le solicita el producto: ','4','2022-02-24','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','185','Pedido','Estimado se le solicita el producto: ','6','2023-04-24','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','185','Pedido','Estimado se le solicita el producto: ','2','2023-06-04','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','185','Pedido','Estimado se le solicita el producto: ','11','2024-02-23','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','185','Pedido','Estimado se le solicita el producto: ','7','2024-06-03','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','186','Pedido','Estimado se le solicita el producto: ','4','2022-06-03','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','186','Pedido','Estimado se le solicita el producto: ','6','2023-11-14','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','186','Pedido','Estimado se le solicita el producto: ','10','2023-11-26','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','186','Pedido','Estimado se le solicita el producto: ','7','2024-01-08','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','186','Pedido','Estimado se le solicita el producto: ','3','2024-06-09','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('8','187','Pedido','Estimado se le solicita el producto: ','2','2022-02-04','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('8','187','Pedido','Estimado se le solicita el producto: ','2','2023-03-27','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('8','187','Pedido','Estimado se le solicita el producto: ','6','2023-12-04','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('8','187','Pedido','Estimado se le solicita el producto: ','7','2024-02-21','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('8','187','Pedido','Estimado se le solicita el producto: ','3','2024-06-04','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','188','Pedido','Estimado se le solicita el producto: ','4','2022-05-03','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','188','Pedido','Estimado se le solicita el producto: ','6','2023-04-12','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','188','Pedido','Estimado se le solicita el producto: ','6','2023-05-26','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','188','Pedido','Estimado se le solicita el producto: ','7','2024-02-06','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','188','Pedido','Estimado se le solicita el producto: ','7','2024-06-01','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','189','Pedido','Estimado se le solicita el producto: ','4','2022-12-03','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','189','Pedido','Estimado se le solicita el producto: ','5','2023-01-23','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','189','Pedido','Estimado se le solicita el producto: ','7','2023-03-04','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','189','Pedido','Estimado se le solicita el producto: ','3','2024-01-26','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','189','Pedido','Estimado se le solicita el producto: ','11','2024-05-28','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('3','190','Pedido','Estimado se le solicita el producto: ','3','2022-01-07','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('3','190','Pedido','Estimado se le solicita el producto: ','6','2023-03-15','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('3','190','Pedido','Estimado se le solicita el producto: ','1','2023-04-22','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('3','190','Pedido','Estimado se le solicita el producto: ','7','2024-02-23','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('3','190','Pedido','Estimado se le solicita el producto: ','3','2024-06-06','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','191','Pedido','Estimado se le solicita el producto: ','8','2022-01-23','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','191','Pedido','Estimado se le solicita el producto: ','6','2023-03-15','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','191','Pedido','Estimado se le solicita el producto: ','3','2023-04-03','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','191','Pedido','Estimado se le solicita el producto: ','3','2024-05-04','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','191','Pedido','Estimado se le solicita el producto: ','10','2024-05-27','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','192','Pedido','Estimado se le solicita el producto: ','4','2022-03-03','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','192','Pedido','Estimado se le solicita el producto: ','9','2023-04-22','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','192','Pedido','Estimado se le solicita el producto: ','3','2023-06-05','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','192','Pedido','Estimado se le solicita el producto: ','4','2024-02-02','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','192','Pedido','Estimado se le solicita el producto: ','10','2024-06-01','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','193','Pedido','Estimado se le solicita el producto: ','4','2022-12-04','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','193','Pedido','Estimado se le solicita el producto: ','6','2023-03-02','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','193','Pedido','Estimado se le solicita el producto: ','2','2023-04-11','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','193','Pedido','Estimado se le solicita el producto: ','11','2023-12-26','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','193','Pedido','Estimado se le solicita el producto: ','7','2024-05-14','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','194','Pedido','Estimado se le solicita el producto: ','4','2022-03-05','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','194','Pedido','Estimado se le solicita el producto: ','6','2023-04-15','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','194','Pedido','Estimado se le solicita el producto: ','6','2023-04-23','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','194','Pedido','Estimado se le solicita el producto: ','7','2024-04-21','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','194','Pedido','Estimado se le solicita el producto: ','7','2024-05-08','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','195','Pedido','Estimado se le solicita el producto: ','3','2022-06-03','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','195','Pedido','Estimado se le solicita el producto: ','9','2023-10-26','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','195','Pedido','Estimado se le solicita el producto: ','7','2023-11-27','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','195','Pedido','Estimado se le solicita el producto: ','7','2024-01-22','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','195','Pedido','Estimado se le solicita el producto: ','4','2024-06-08','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','1','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','2','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','3','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','4','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','5','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','6','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','7','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','8','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','9','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','10','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','11','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','12','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','13','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','14','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','15','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','16','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','17','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','18','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','19','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','20','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','21','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','22','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','23','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','24','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','25','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','26','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','27','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','28','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','29','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','30','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','31','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','32','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','33','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','34','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','35','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','36','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','37','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','38','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','39','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','40','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','41','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','42','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','43','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','44','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','45','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','46','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','47','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','48','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','49','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','50','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','51','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','52','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','53','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','54','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','55','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','56','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','57','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','58','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','59','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','60','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','61','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','62','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','63','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','64','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','65','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','66','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','67','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','68','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','69','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','70','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','71','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','72','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','73','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','74','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','75','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','76','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','77','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','78','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','79','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','80','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','81','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','82','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','83','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','84','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','85','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','86','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','87','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','88','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','89','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','90','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','91','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','92','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','93','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','94','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','95','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','96','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','97','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','98','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','99','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','100','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','101','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','102','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','103','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','104','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','105','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','106','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','107','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','108','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','109','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','110','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','111','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','112','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','113','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','114','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','115','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','116','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','117','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','118','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','119','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','120','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','121','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','122','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','123','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','124','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','125','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','126','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','127','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','128','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','129','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','130','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','131','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','132','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','133','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','134','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','135','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','136','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','137','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','138','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','139','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','140','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','141','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','142','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','143','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','144','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','145','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','146','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','147','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','148','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','149','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','150','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','151','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','152','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','153','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','154','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','155','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','156','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','157','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','158','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','159','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','160','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','161','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','162','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','163','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','164','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','165','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','166','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','167','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','168','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','169','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','170','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','171','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','172','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','173','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','174','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','175','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','176','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','177','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','178','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','179','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','180','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','181','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','182','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','183','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','184','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','185','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','186','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','187','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','188','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','189','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','190','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','191','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','192','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','193','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','194','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','195','Pedido','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','193','Devolución','Se encontro defectos en el producto: ','3','2024-07-07','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','194','Devolución','Se encontro defectos en el producto: ','2','2024-07-07','Finalizado')");
        DB::statement("INSERT INTO Solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','195','Devolución','Se encontro defectos en el producto: ','1','2024-07-07','Finalizado')");
    }

    public function down(): void
    {
        Schema::dropIfExists('solicitud');
    }
};
