<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('solicitud', function (Blueprint $table) {
            $table->engine="InnoDB";
            $table->id();
            $table->foreignId('usuario_id')
                ->constrained('equipologistica')
                ->onDelete('cascade');
            $table->foreignId('producto_id')
                ->constrained('producto')
                ->onDelete('cascade');
            $table->string('tipo', 20);
            $table->string('descripcion', 250);
            $table->integer('cantidad');
            $table->date('fecha');
            $table->string('estado', 50);
        });

        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','1','Compra','Estimado se le solicita el producto: ','4','2022-03-05','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','1','Compra','Estimado se le solicita el producto: ','6','2023-05-15','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','1','Compra','Estimado se le solicita el producto: ','6','2023-06-03','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','1','Compra','Estimado se le solicita el producto: ','7','2024-02-01','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','1','Compra','Estimado se le solicita el producto: ','7','2024-06-08','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','2','Compra','Estimado se le solicita el producto: ','5','2022-04-03','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','2','Compra','Estimado se le solicita el producto: ','7','2023-02-11','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','2','Compra','Estimado se le solicita el producto: ','4','2023-04-03','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','2','Compra','Estimado se le solicita el producto: ','3','2024-02-04','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','2','Compra','Estimado se le solicita el producto: ','1','2024-03-05','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('3','3','Compra','Estimado se le solicita el producto: ','3','2022-07-04','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('3','3','Compra','Estimado se le solicita el producto: ','5','2023-05-12','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('3','3','Compra','Estimado se le solicita el producto: ','2','2023-08-06','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('3','3','Compra','Estimado se le solicita el producto: ','5','2024-03-18','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('3','3','Compra','Estimado se le solicita el producto: ','5','2024-05-29','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','4','Compra','Estimado se le solicita el producto: ','10','2022-05-26','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','4','Compra','Estimado se le solicita el producto: ','6','2023-05-05','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','4','Compra','Estimado se le solicita el producto: ','4','2023-06-23','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','4','Compra','Estimado se le solicita el producto: ','8','2024-03-26','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','4','Compra','Estimado se le solicita el producto: ','2','2024-07-08','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','5','Compra','Estimado se le solicita el producto: ','4','2022-01-12','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','5','Compra','Estimado se le solicita el producto: ','5','2023-10-28','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','5','Compra','Estimado se le solicita el producto: ','1','2023-11-25','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','5','Compra','Estimado se le solicita el producto: ','5','2024-02-21','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','5','Compra','Estimado se le solicita el producto: ','5','2024-06-03','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','6','Compra','Estimado se le solicita el producto: ','4','2022-07-01','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','6','Compra','Estimado se le solicita el producto: ','3','2023-10-13','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','6','Compra','Estimado se le solicita el producto: ','3','2023-12-01','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','6','Compra','Estimado se le solicita el producto: ','4','2024-04-24','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','6','Compra','Estimado se le solicita el producto: ','6','2024-05-27','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','7','Compra','Estimado se le solicita el producto: ','4','2022-03-26','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','7','Compra','Estimado se le solicita el producto: ','3','2023-04-15','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','7','Compra','Estimado se le solicita el producto: ','9','2023-09-03','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','7','Compra','Estimado se le solicita el producto: ','2','2024-01-22','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','7','Compra','Estimado se le solicita el producto: ','12','2024-06-08','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','8','Compra','Estimado se le solicita el producto: ','4','2022-03-03','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','8','Compra','Estimado se le solicita el producto: ','6','2023-03-01','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','8','Compra','Estimado se le solicita el producto: ','6','2023-10-05','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','8','Compra','Estimado se le solicita el producto: ','7','2024-03-25','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','8','Compra','Estimado se le solicita el producto: ','7','2024-06-06','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','9','Compra','Estimado se le solicita el producto: ','4','2022-07-01','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','9','Compra','Estimado se le solicita el producto: ','8','2023-05-13','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','9','Compra','Estimado se le solicita el producto: ','4','2023-05-25','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','9','Compra','Estimado se le solicita el producto: ','3','2024-05-05','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','9','Compra','Estimado se le solicita el producto: ','11','2024-05-28','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','10','Compra','Estimado se le solicita el producto: ','5','2022-04-07','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','10','Compra','Estimado se le solicita el producto: ','8','2023-10-20','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','10','Compra','Estimado se le solicita el producto: ','3','2023-11-25','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','10','Compra','Estimado se le solicita el producto: ','7','2024-01-01','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','10','Compra','Estimado se le solicita el producto: ','7','2024-05-29','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','185','Compra','Estimado se le solicita el producto: ','4','2022-02-24','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','185','Compra','Estimado se le solicita el producto: ','6','2023-04-24','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','185','Compra','Estimado se le solicita el producto: ','2','2023-06-04','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','185','Compra','Estimado se le solicita el producto: ','11','2024-02-23','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','185','Compra','Estimado se le solicita el producto: ','7','2024-06-03','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','186','Compra','Estimado se le solicita el producto: ','4','2022-06-03','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','186','Compra','Estimado se le solicita el producto: ','6','2023-11-14','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','186','Compra','Estimado se le solicita el producto: ','10','2023-11-26','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','186','Compra','Estimado se le solicita el producto: ','7','2024-01-08','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','186','Compra','Estimado se le solicita el producto: ','3','2024-06-09','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('8','187','Compra','Estimado se le solicita el producto: ','2','2022-02-04','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('8','187','Compra','Estimado se le solicita el producto: ','2','2023-03-27','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('8','187','Compra','Estimado se le solicita el producto: ','6','2023-12-04','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('8','187','Compra','Estimado se le solicita el producto: ','7','2024-02-21','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('8','187','Compra','Estimado se le solicita el producto: ','3','2024-06-04','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','188','Compra','Estimado se le solicita el producto: ','4','2022-05-03','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','188','Compra','Estimado se le solicita el producto: ','6','2023-04-12','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','188','Compra','Estimado se le solicita el producto: ','6','2023-05-26','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','188','Compra','Estimado se le solicita el producto: ','7','2024-02-06','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','188','Compra','Estimado se le solicita el producto: ','7','2024-06-01','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','189','Compra','Estimado se le solicita el producto: ','4','2022-12-03','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','189','Compra','Estimado se le solicita el producto: ','5','2023-01-23','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','189','Compra','Estimado se le solicita el producto: ','7','2023-03-04','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','189','Compra','Estimado se le solicita el producto: ','3','2024-01-26','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('2','189','Compra','Estimado se le solicita el producto: ','11','2024-05-28','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('3','190','Compra','Estimado se le solicita el producto: ','3','2022-01-07','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('3','190','Compra','Estimado se le solicita el producto: ','6','2023-03-15','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('3','190','Compra','Estimado se le solicita el producto: ','1','2023-04-22','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('3','190','Compra','Estimado se le solicita el producto: ','7','2024-02-23','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('3','190','Compra','Estimado se le solicita el producto: ','3','2024-06-06','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','191','Compra','Estimado se le solicita el producto: ','8','2022-01-23','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','191','Compra','Estimado se le solicita el producto: ','6','2023-03-15','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','191','Compra','Estimado se le solicita el producto: ','3','2023-04-03','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','191','Compra','Estimado se le solicita el producto: ','3','2024-05-04','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','191','Compra','Estimado se le solicita el producto: ','10','2024-05-27','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','192','Compra','Estimado se le solicita el producto: ','4','2022-03-03','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','192','Compra','Estimado se le solicita el producto: ','9','2023-04-22','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','192','Compra','Estimado se le solicita el producto: ','3','2023-06-05','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','192','Compra','Estimado se le solicita el producto: ','4','2024-02-02','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('4','192','Compra','Estimado se le solicita el producto: ','10','2024-06-01','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','193','Compra','Estimado se le solicita el producto: ','4','2022-12-04','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','193','Compra','Estimado se le solicita el producto: ','6','2023-03-02','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','193','Compra','Estimado se le solicita el producto: ','2','2023-04-11','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','193','Compra','Estimado se le solicita el producto: ','11','2023-12-26','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('6','193','Compra','Estimado se le solicita el producto: ','7','2024-05-14','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','194','Compra','Estimado se le solicita el producto: ','4','2022-03-05','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','194','Compra','Estimado se le solicita el producto: ','6','2023-04-15','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','194','Compra','Estimado se le solicita el producto: ','6','2023-04-23','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','194','Compra','Estimado se le solicita el producto: ','7','2024-04-21','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('5','194','Compra','Estimado se le solicita el producto: ','7','2024-05-08','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','195','Compra','Estimado se le solicita el producto: ','3','2022-06-03','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','195','Compra','Estimado se le solicita el producto: ','9','2023-10-26','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','195','Compra','Estimado se le solicita el producto: ','7','2023-11-27','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','195','Compra','Estimado se le solicita el producto: ','7','2024-01-22','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('7','195','Compra','Estimado se le solicita el producto: ','4','2024-06-08','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','1','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','2','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','3','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','4','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','5','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','6','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','7','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','8','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','9','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','10','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','11','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','12','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','13','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','14','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','15','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','16','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','17','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','18','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','19','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','20','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','21','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','22','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','23','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','24','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','25','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','26','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','27','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','28','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','29','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','30','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','31','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','32','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','33','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','34','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','35','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','36','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','37','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','38','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','39','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','40','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','41','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','42','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','43','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','44','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','45','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','46','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','47','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','48','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','49','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','50','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','51','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','52','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','53','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','54','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','55','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','56','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','57','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','58','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','59','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','60','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','61','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','62','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','63','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','64','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','65','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','66','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','67','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','68','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','69','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','70','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','71','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','72','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','73','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','74','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','75','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','76','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','77','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','78','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','79','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','80','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','81','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','82','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','83','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','84','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','85','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','86','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','87','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','88','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','89','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','90','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','91','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','92','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','93','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','94','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','95','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','96','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','97','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','98','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','99','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','100','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','101','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','102','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','103','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','104','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','105','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','106','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','107','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','108','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','109','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','110','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','111','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','112','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','113','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','114','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','115','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','116','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','117','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','118','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','119','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','120','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','121','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','122','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','123','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','124','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','125','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','126','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','127','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','128','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','129','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','130','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','131','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','132','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','133','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','134','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','135','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','136','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','137','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','138','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','139','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','140','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','141','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','142','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','143','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','144','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','145','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','146','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','147','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','148','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','149','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','150','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','151','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','152','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','153','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','154','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','155','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','156','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','157','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','158','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','159','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','160','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','161','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','162','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','163','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','164','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','165','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','166','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','167','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','168','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','169','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','170','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','171','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','172','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','173','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','174','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','175','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','176','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','177','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','178','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','179','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','180','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','181','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','182','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','183','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','184','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','185','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','186','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','187','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','188','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','189','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','190','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','191','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','192','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','193','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','194','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','195','Compra','Estimado se le solicita el producto: ','20','2021-12-10','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','193','Devolución','Se encontro defectos en el producto: ','3','2024-07-07','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','194','Devolución','Se encontro defectos en el producto: ','2','2024-07-07','Finalizado')");
        DB::statement("INSERT INTO solicitud (usuario_id,producto_id,tipo,descripcion,cantidad,fecha,estado) VALUES ('1','195','Devolución','Se encontro defectos en el producto: ','1','2024-07-07','Finalizado')");
    }

    public function down(): void
    {
        Schema::dropIfExists('solicitud');
    }
};
