<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('producto', function (Blueprint $table) {
            $table->engine = "InnoDB";
            $table->id();
            $table->string('nombre', 80);
            $table->string('descripcion', 150);
            $table->integer('stock');
            $table->foreignId('proveedor_id')
                ->constrained('proveedor')
                ->onDelete('cascade');
        });
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Sony WH-1000XM4', 'Audífonos inalámbricos con cancelación de ruido y calidad de sonido excepcional','20','2')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Sony WH-1000XM4', 'Audífonos inalámbricos con cancelación de ruido y calidad de sonido excepcional','20','2')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Bose QuietComfort 35 II', 'Audífonos Bluetooth con cancelación activa de ruido y micrófono integrado','20','3')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Apple AirPods Pro', 'Audífonos inalámbricos con ajuste personalizado y cancelación activa de ruido','20','6')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('JBL Flip 5', 'Parlante portátil resistente al agua con sonido potente y batería de larga duración','20','1')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Sony SRS-XB43', 'Parlante Bluetooth con extra bass y resistencia al agua y al polvo','20','2')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Bose SoundLink Color II', 'Parlante Bluetooth compacto con sonido envolvente y diseño elegante','20','3')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Blue Yeti', 'Micrófono USB versátil con calidad de grabación profesional y múltiples patrones de captación','20','24')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Sennheiser XS 1', 'Micrófono dinámico de mano, con patrón polar cardioide, interruptor de silencio silencioso, clip de micrófono y bolsa de transporte.','20','4')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Rode NT-USB', 'Micrófono USB con calidad de estudio y filtro pop integrado para grabaciones claras','20','25')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Amazon Basics 3.5mm Male to Male Stereo Audio Cable', 'Cable de audio de 1.2 metros para conectar dispositivos','20','15')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Bose SoundLink Flex', 'Funda de transporte para parlantes Bose con protección y estilo','20','3')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Focusrite Scarlett Solo', 'Interfaz de audio USB para grabación de alta calidad en estudios caseros','20','26')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Samsung HW-Q80R', 'Barra de sonido con tecnología Dolby Atmos y sonido envolvente','20','5')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('LG SN6Y', 'Barras de sonido con potencia de 420W y sonido envolvente 3.1','20','22')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Bose Soundbar 500', 'Barra de sonido inteligente con Amazon Alexa y sonido de calidad superior','20','3')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Apple iPhone 14', 'Smartphone de alta gama con cámara dual y chip A15 Bionic','20','6')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Samsung Galaxy S23', 'Celular insignia con pantalla AMOLED y rendimiento potente','20','5')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Google Pixel 7', 'Smartphone con cámara avanzada y experiencia Android pura','20','16')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Spigen Tough Armor', 'Funda protectora resistente para iPhone con diseño elegante','20','24')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('OtterBox Defender', 'Funda robusta para Samsung Galaxy que ofrece máxima protección','20','24')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Case-Mate Tough Clear', 'Funda transparente y duradera para resaltar el diseño original del celular','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('ZAGG InvisibleShield', 'Protector de pantalla de alta definición que previene rayones','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Spigen Glas.tr', 'Cristal templado de 9H para máxima protección de pantalla','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Belkin InvisiGlass Ultra', 'Mica para pantalla ultra delgada y resistente a los impactos','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Apple Watch Series 8', 'Reloj inteligente con monitoreo de salud y seguimiento de actividad','20','6')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Samsung Galaxy Watch 5', 'Smartwatch con GPS y funciones avanzadas de salud y fitness','20','5')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Fitbit Versa 4', 'Reloj inteligente con seguimiento de actividad y notificaciones','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Anker PowerCore 10000', 'Cargador portátil compacto con capacidad de 10000mAh','20','9')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('RAVPower 26800mAh', 'Batería externa de gran capacidad con múltiples puertos de carga','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Xiaomi Mi Power Bank 3', 'Cargador portátil con doble salida USB y carga rápida','20','7')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('UGREEN Soporte para teléfono', 'Soporte ajustable para escritorio, ideal para videollamadas','20','24')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Anker Soporte para celular', 'Base de carga con soporte para smartphone y tablet','20','9')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('OMOTON Soporte Ajustable', 'Soporte ergonómico para celular, compatible con la mayoría de modelos','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Apple 20W USB-C Power Adapter', 'Cargador rápido para iPhone y dispositivos compatibles','20','6')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Anker 30W USB-C Charger', 'Cargador compacto de alta velocidad para varios dispositivos','20','9')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Samsung Adaptive Fast Charger', 'Cargador rápido compatible con la mayoría de smartphones Samsung','20','5')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Amazon Basics USB-C to USB-A Cable', 'Cable USB de 1.8 metros para transferencia de datos','20','15')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Anker Powerline II Lightning Cable', 'Cable Lightning de 1 metro con garantía de por vida','20','9')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Belkin Mixit DuraTek Lightning Cable', 'Cable de carga Lightning duradero y flexible','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('SanDisk Ultra microSDXC', 'Tarjeta de memoria de 128GB para almacenamiento en dispositivos móviles','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Samsung EVO Select 64GB', 'Tarjeta microSD con alta velocidad de lectura y escritura','20','5')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Kingston Canvas Select Plus 32GB', 'Tarjeta de memoria con rendimiento confiable para fotografías y videos','20','14')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Moment Lens M-Cap', 'Protector de lente para evitar rayones en cámaras de smartphones','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('K&F Concept Protector de Lente', 'Funda de protección para cámaras DSLR y mirrorless','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Neewer Protector para Cámaras', 'Protección de cámara universal para la mayoría de modelos','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('PopSocket', 'Soporte para celular que proporciona un mejor agarre y se puede usar como soporte','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Belkin Car Vent Mount', 'Soporte para celular que se adhiere a la rejilla de ventilación del auto','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Razer Phone Cooler Chroma', 'Ventilador para celular diseñado para gaming, reduce la temperatura','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Alienware M15 R6', 'Laptop gamer con pantalla de 15.6 pulgadas, procesador Intel Core i7 y gráfica NVIDIA RTX 3060','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('ASUS ROG Zephyrus G14', 'Laptop gamer ultradelgada con procesador AMD Ryzen 9 y gráfica NVIDIA RTX 3060','20','13')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('MSI GF65 Thin', 'Laptop gamer con procesador Intel Core i5 y gráfica NVIDIA GTX 1660 Ti','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('LG UltraGear 27GN950', 'Monitor gamer de 27 pulgadas con resolución 4K y tasa de refresco de 144Hz','20','22')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Samsung Odyssey G9', 'Monitor curvo de 49 pulgadas con resolución Dual QHD y tasa de refresco de 240Hz','20','5')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('ASUS TUF Gaming VG27AQ', 'Monitor de 27 pulgadas con resolución 1440p y 165Hz, ideal para juegos de alta velocidad','20','13')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Razer BlackWidow V3', 'Teclado mecánico gamer con iluminación RGB y switches táctiles de alto rendimiento','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Logitech G502 HERO', 'Ratón gamer con sensor HERO de 25,600 DPI, personalizable y con pesos ajustables','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('HyperX Cloud Alpha', 'Audífonos gamer con sonido envolvente y almohadillas de cuero para mayor comodidad','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('AMD Ryzen 7 5800X', 'Procesador de 8 núcleos y 16 hilos, ideal para gaming de alto rendimiento','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('NVIDIA GeForce RTX 3080', 'Tarjeta gráfica con arquitectura Ampere y 10GB de VRAM, ideal para gaming en 4K','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Corsair Vengeance RGB Pro 16GB', 'Memoria RAM de alta velocidad con iluminación RGB para una experiencia de juego superior','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('DXRacer Master', 'Silla gamer ergonómica con soporte lumbar y reposabrazos ajustables','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Secretlab Titan EVO 2022', 'Silla gamer con soporte lumbar integrado y múltiples ajustes para comodidad','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Arozzi Arena', 'Mesa gamer con superficie espaciosa y resistente al agua, ideal para setups gaming','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('PlayStation 5', 'Consola de última generación con soporte para juegos 4K y ray tracing','3','2')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Xbox Series X', 'Consola de alto rendimiento con soporte para juegos en 4K y almacenamiento SSD de 1TB','2','23')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Nintendo Switch OLED', 'Consola híbrida con pantalla OLED y soporte para modo portátil y de sobremesa','1','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Oculus Quest 2', 'Casco de realidad virtual autónomo con pantalla de alta resolución y 128GB de almacenamiento','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('HTC Vive Pro', 'Sistema de realidad virtual con tracking de precisión y alta resolución para PC','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('PlayStation VR2', 'Casco de realidad virtual compatible con la consola PS5 y gráficos avanzados','20','2')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Control Inalámbrico DualSense', 'Control inalámbrico para PS5 con retroalimentación háptica y gatillos adaptativos','20','2')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Xbox Elite Wireless Controller Series 2', 'Controlador premium con personalización avanzada y batería de larga duración','20','23')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Nintendo Switch Pro Controller', 'Controlador inalámbrico para Nintendo Switch con diseño ergonómico','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Elgato Stream Deck', 'Panel de control personalizable para streaming y productividad','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Blue Yeti X', 'Micrófono USB de alta calidad ideal para streaming y grabación de voz','20','24')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Logitech C920 Pro', 'Cámara web HD 1080p ideal para streaming y videollamadas','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Funko Pop! Geralt of Rivia', 'Figura coleccionable de Geralt de Rivia de la serie The Witcher','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Figura Nendoroid Link', 'Figura articulada de Link, basada en el juego The Legend of Zelda','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Amiibo Mario', 'Figura coleccionable Amiibo de Mario compatible con múltiples juegos de Nintendo','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Apple iPad Air 10.9', 'Tablet con pantalla de 10.9 pulgadas, chip A14 Bionic, ideal para productividad y entretenimiento','20','6')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Wacom Intuos Pro M', 'Tableta gráfica profesional de tamaño mediano con sensibilidad a la presión','20','10')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Samsung Galaxy Tab S7', 'Tablet con pantalla de 11 pulgadas, procesador Snapdragon 865+ y lápiz S Pen incluido','20','5')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Dell XPS 13', 'Laptop ultradelgada de 13 pulgadas con procesador Intel Core i7 y pantalla InfinityEdge','20','12')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('HP Spectre x360', 'Laptop convertible con pantalla táctil de 13.3 pulgadas, ideal para trabajo y entretenimiento','20','11')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Lenovo ThinkPad X1 Carbon', 'Laptop de 14 pulgadas, diseño ligero y duradero con procesador Intel Core i5','20','24')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('HP Pavilion Desktop', 'PC de escritorio con procesador Intel Core i5 y almacenamiento de 1TB','20','11')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Acer Aspire TC', 'Computadora de escritorio con 8GB RAM, ideal para uso en el hogar y oficina','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Apple iMac 24', 'PC de escritorio todo en uno con pantalla Retina 4.5K de 24 pulgadas y chip M1','20','6')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Canon PIXMA G3110', 'Impresora multifuncional con sistema de tinta recargable, ideal para alta calidad','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('HP DeskJet 3755', 'Impresora compacta y todo en uno con capacidad de impresión inalámbrica','20','11')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Epson EcoTank L3150', 'Impresora multifuncional con sistema de tanque de tinta de alta capacidad','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Samsung Odyssey G5', 'Monitor curvo de 27 pulgadas, resolución WQHD y frecuencia de actualización de 144Hz','20','5')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('LG UltraFine 27UL850-W', 'Monitor 4K UHD de 27 pulgadas, compatible con HDR10 y USB-C','20','22')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Dell P2419H', 'Monitor de 24 pulgadas, diseño sin bordes y calidad de imagen Full HD','20','12')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Logitech MX Master 3', 'Ratón ergonómico inalámbrico con precisión avanzada y control por gestos','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Razer BlackWidow V3', 'Teclado mecánico para gaming con teclas retroiluminadas personalizables','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Microsoft Surface Pen', 'Lápiz digital compatible con dispositivos Surface, sensible a la presión','20','23')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Sabrent HDD Docking Station', 'Estación de acoplamiento para discos duros, compatible con SSD y HDD de 2.5/3.5 pulgadas','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('ORICO 2.5 Enclosure', 'Carcasa para discos duros de 2.5 pulgadas con conexión USB 3.0','20','24')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('UGREEN USB to SATA', 'Adaptador USB a SATA para conectar discos duros externos','20','24')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Sandisk Ultra Fit 64GB', 'Unidad flash USB 3.1 de tamaño compacto y alta velocidad de transferencia','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Kingston DataTraveler 128GB', 'Memoria USB de alta capacidad con diseño duradero y seguro','20','14')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Corsair Flash Voyager GTX 256GB', 'Unidad USB de alta velocidad, ideal para transferir archivos grandes','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('WD My Passport 1TB', 'Disco duro externo con protección de contraseña y software de respaldo automático','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Seagate Backup Plus Slim 2TB', 'Disco portátil de alta capacidad, compatible con Mac y Windows','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Toshiba Canvio Advance 4TB', 'Disco duro externo con diseño elegante y gran capacidad de almacenamiento','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Samsung EVO Select 128GB', 'Tarjeta microSD de alta velocidad, ideal para smartphones y cámaras','20','5')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Sandisk Extreme Pro 64GB', 'Tarjeta SD con alta velocidad de lectura/escritura, ideal para video 4K','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Lexar Professional 1000x 32GB', 'Tarjeta SD de alto rendimiento, ideal para fotografía profesional','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Screen Mom Cleaner Kit', 'Kit de limpieza para pantallas de dispositivos electrónicos, sin químicos agresivos','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('WHOOSH! Screen Shine', 'Limpiador de pantalla antibacteriano, seguro para todo tipo de dispositivos','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Endust for Electronics', 'Aerosol limpiador para pantallas y equipos electrónicos con paño antiestático','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Microsoft Office 365', 'Licencia anual con aplicaciones de productividad para escritorio y en la nube','20','23')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Norton 360 Deluxe', 'Suite de seguridad digital completa con protección antivirus y VPN','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Adobe Creative Cloud', 'Licencia anual para software de diseño y edición profesional, con acceso a múltiples aplicaciones','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Amazon Fire TV Stick 4K', 'Convertidor de streaming en 4K con control por voz Alexa y acceso a múltiples plataformas','20','15')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Google Chromecast with Google TV', 'Convertidor de streaming con soporte para 4K, con interfaz de Google TV','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Roku Express 4K+', 'Dispositivo de streaming 4K con control remoto y compatibilidad con asistentes de voz','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Amazon Echo Dot 4th Gen', 'Parlante inteligente con Alexa y diseño compacto','20','15')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Google Nest Audio', 'Parlante inteligente con Google Assistant y sonido de alta calidad','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Apple HomePod mini', 'Parlante inteligente con Siri y sonido envolvente en un tamaño compacto','20','6')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('iRobot Roomba i7+', 'Robot aspirador con auto-vaciado y control por aplicación','20','8')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Xiaomi Mi Robot Vacuum Mop 2', 'Aspiradora y trapeadora robot con mapeo láser y control remoto','20','7')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Ecovacs Deebot OZMO T8 AIVI', 'Robot aspirador con detección de objetos y trapeado avanzado','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Etekcity Smart Scale ESF37', 'Balanza inteligente con Bluetooth y aplicación para monitoreo de peso y salud','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Withings Body+', 'Balanza inteligente Wi-Fi que mide peso, grasa y composición corporal','20','24')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('RENPHO Body Fat Scale', 'Balanza inteligente con análisis de composición corporal y conectividad Bluetooth','20','25')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Philips Hue White and Color Ambiance', 'Bombilla inteligente con ajuste de color y control por aplicación','20','17')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Yeelight Smart LED Bulb 1S', 'Bombilla inteligente LED con control por app y compatibilidad con asistentes','20','24')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('TP-Link Kasa Smart Light Bulb', 'Bombilla inteligente con ajuste de brillo y compatibilidad con Alexa y Google','20','18')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Nanoleaf Shapes Hexagons', 'Paneles de luz LED modulares que permiten crear diseños personalizados','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Govee Glide Wall Light', 'Luz de pared LED personalizable con control por app y modos de escena','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('LIFX Beam Kit', 'Sistema de iluminación modular y ajustable, controlable a través de app y asistentes de voz','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('TP-Link Kasa Smart Plug', 'Enchufe inteligente con control remoto y compatibilidad con Alexa y Google Assistant','20','18')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Amazon Smart Plug', 'Enchufe inteligente diseñado para Alexa y fácil configuración','20','15')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Gosund Smart Plug', 'Enchufe inteligente con control remoto y temporizador, compatible con asistentes de voz','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Leviton Decora Smart', 'Interruptor inteligente compatible con Alexa y Google Assistant','20','1')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Lutron Caseta Wireless', 'Interruptor inteligente con control remoto y compatibilidad con asistentes de voz','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('TP-Link Kasa Smart Switch', 'Interruptor inteligente de fácil instalación y control remoto','20','18')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Ring Video Doorbell 4', 'Timbre inteligente con cámara HD y comunicación bidireccional','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Google Nest Cam (Indoor, Wired)', 'Cámara de seguridad para interiores con detección de movimiento y audio','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Eufy Security SoloCam E40', 'Cámara de seguridad inalámbrica con visión nocturna y almacenamiento local','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Netgear Orbi Mesh WiFi System', 'Sistema de WiFi en malla con cobertura extendida y control por app','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('TP-Link Deco X60', 'Sistema de WiFi 6 en malla, ideal para cobertura en todo el hogar','20','18')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Google Nest WiFi', 'Sistema de WiFi en malla con asistente Google integrado en algunos nodos','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Insta360 ONE X2', 'Cámara de acción de 360 grados con estabilización avanzada y resistente al agua','20','19')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Insta360 GO 2', 'Mini cámara de acción portátil, ideal para capturar momentos en primera persona','20','19')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Insta360 ONE R', 'Cámara modular con opciones de lente intercambiables, incluyendo 360 grados y gran angular','20','19')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('GoPro HERO11 Black', 'Cámara de acción con grabación en 5.3K y estabilización avanzada','20','20')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('GoPro HERO10 Black', 'Cámara de acción con procesador rápido y grabación en 5.3K Ultra HD','20','20')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('GoPro MAX', 'Cámara de 360 grados con modo de cámara HERO y estabilización de nivel profesional','20','20')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('DJI Osmo Action 3', 'Cámara de acción con doble pantalla y grabación 4K HDR','20','21')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Sony RX0 II', 'Cámara de acción ultra compacta con lente Zeiss y grabación en 4K','20','2')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Akaso Brave 7 LE', 'Cámara de acción resistente al agua con estabilización EIS y pantalla dual','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('GoPro Media Mod', 'Accesorio modular para HERO que incluye micrófono direccional','20','20')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('DJI Osmo Action Chest Mount', 'Montura para el pecho compatible con DJI Osmo Action','20','21')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Insta360 Selfie Stick Invisible', 'Palo selfie invisible compatible con cámaras Insta360 para tomas en 360 grados','20','19')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('DJI Mini 3 Pro', 'Drone compacto con cámara 4K, sensores de detección y modo inteligente','20','21')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('DJI Air 2S', 'Drone con cámara de 1 pulgada y grabación en 5.4K, ideal para fotografía aérea','20','21')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Holy Stone HS720E', 'Drone plegable con estabilización EIS y cámara Ultra HD 4K','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('DJI Fly More Kit', 'Kit de accesorios para DJI Mini 3 Pro con baterías adicionales y cargador','20','21')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Propel Zipp Nano', 'Mini drone con repuestos y accesorios para entrenamiento','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Sunnylife Landing Pad', 'Alfombra de aterrizaje portátil para drones, compatible con varias marcas','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Sandisk Extreme 128GB', 'Tarjeta microSD de alta velocidad, ideal para cámaras de acción y drones','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Samsung EVO Select 256GB', 'Tarjeta microSD con velocidad de lectura rápida, resistente al agua y temperaturas extremas','20','5')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Lexar Professional 1000x 64GB', 'Tarjeta de memoria microSD con velocidad UHS-II, ideal para grabaciones en 4K','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('WD My Passport 2TB', 'Disco duro portátil con copia de seguridad automática y encriptación','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Seagate Expansion Portable 1TB', 'Disco duro externo portátil, compatible con múltiples dispositivos','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Lacie Rugged Mini 4TB', 'Disco duro externo portátil con resistencia a caídas y conectividad USB-C','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Samsung QN90A', 'Televisor 4K QLED de 55 pulgadas con tecnología Neo QLED y Dolby Atmos','20','5')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Sony A80J', 'Televisor OLED 4K de 65 pulgadas con sonido acústico y diseño elegante','20','2')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('LG OLED C1', 'Televisor OLED 4K de 55 pulgadas, con compatibilidad HDR y gaming optimizado','20','22')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Epson Home Cinema 2150', 'Proyector de 1080p con tecnología de proyección 3LCD y conectividad inalámbrica','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('BenQ HT3550', 'Proyector 4K HDR con calidad de imagen cinematográfica y brillo potente','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Anker Nebula Capsule', 'Proyector portátil con batería y conectividad inalámbrica, ideal para entretenimiento en movimiento','20','9')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Zinus Tessa TV Stand', 'Rack de TV de madera con diseño moderno, adecuado para pantallas de hasta 55 pulgadas','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Furinno Turn-S-Tube', 'Rack de TV de estilo contemporáneo, fácil de ensamblar y compacto','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Walker Edison Furniture Company', 'Rack de TV de 58 pulgadas, de estilo industrial con estantes de vidrio','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Amazon Fire TV Stick 4K', 'Dispositivo de streaming 4K con control remoto y acceso a múltiples plataformas','20','15')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Google Chromecast with Google TV', 'Convertidor inteligente con control remoto y acceso a aplicaciones de streaming','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Roku Streaming Stick+', 'Convertidor de streaming 4K con acceso a miles de canales de entretenimiento','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Sanus VLT6-B1', 'Soporte de pared para TV de hasta 90 pulgadas, con inclinación y ajuste de altura','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Mount-It! MI-43111', 'Soporte de pared para TV de 32 a 70 pulgadas, con giro y ajuste de inclinación','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('AVF BTV100-B', 'Soporte de TV de mesa con diseño moderno, ideal para pantallas planas','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('AmazonBasics High-Speed HDMI Cable', 'Cable HDMI de 2 metros, compatible con todas las versiones HDMI','20','15')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Cable Matters Active HDMI to HDMI Cable', 'Cable HDMI activo de 3 metros, ideal para largas distancias','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Ultra Clarity Cables HDMI Cable', 'Cable HDMI de 1.8 metros, con soporte para 4K y 3D','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Logitech Harmony Elite', 'Control remoto universal con pantalla táctil y compatibilidad con dispositivos inteligentes','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('GE Universal Remote Control', 'Control remoto universal compatible con la mayoría de los dispositivos de TV','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Inateck TV Remote Cover', 'Funda protectora para control remoto, con diseño antideslizante','20','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Samsung HW-Q950A', 'Barras de sonido 11.1.4 con Dolby Atmos y conectividad Bluetooth','20','5')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Bose Soundbar 700', 'Barra de sonido premium con cancelación de ruido y control por voz','20','3')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('LG SN11RG', 'Barra de sonido 7.1.4 con Dolby Atmos y DTS:X para un sonido envolvente','20','22')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('APC BE600M1', 'Estabilizador de voltaje y protector de sobretensiones para equipos electrónicos','17','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Sansui Power Strip', 'Extensión de corriente con 6 tomas y protección contra sobrecargas','18','27')");
        DB::statement("INSERT INTO Producto (nombre,descripcion,stock,proveedor_id) VALUES ('Tripp Lite Isobar Surge Protector', 'Protector contra sobrecargas con 8 tomas y filtrado de ruido','19','27')");
    }
    
    public function down(): void
    {
        Schema::dropIfExists('producto');
    }
};

